/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

/**
 *
 * @author manuelalejandro
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNroHist = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        cmbTCedPac = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblEstPorque = new javax.swing.JLabel();
        tbtnEst = new javax.swing.JToggleButton();
        jtxtEstDes = new javax.swing.JScrollPane();
        txtEstDes = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tbtnMed = new javax.swing.JToggleButton();
        lblMedCuales = new javax.swing.JLabel();
        jtxtMedDes = new javax.swing.JScrollPane();
        txtMedDes = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtDolDes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rbtnPolvo = new javax.swing.JRadioButton();
        rbtnMed = new javax.swing.JRadioButton();
        rbtnAlimentos = new javax.swing.JRadioButton();
        txtAlerDes = new javax.swing.JTextField();
        rbtnOtros = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tbtnRonca = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        tbtnResp = new javax.swing.JToggleButton();
        cmbResCuando = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tbtnResfrio = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        tbtnAmigd = new javax.swing.JToggleButton();
        jtxtMastDes = new javax.swing.JScrollPane();
        txtMastDes = new javax.swing.JTextArea();
        lblMastPorque = new javax.swing.JLabel();
        tbtnMast = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tbtnOrl = new javax.swing.JToggleButton();
        lblOrlPorque = new javax.swing.JLabel();
        jtxtOrlDes = new javax.swing.JScrollPane();
        txtOrlDes = new javax.swing.JTextArea();
        rbtnCirugia = new javax.swing.JRadioButton();
        rbtnAmigd = new javax.swing.JRadioButton();
        rbtnAdenoi = new javax.swing.JRadioButton();
        fchOrl = new com.toedter.calendar.JDateChooser();
        lblOrlCuando = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnasma = new javax.swing.JRadioButton();
        rbtndiabetes = new javax.swing.JRadioButton();
        rbtnanemia = new javax.swing.JRadioButton();
        rbtnherpes = new javax.swing.JRadioButton();
        rbtnepilepsia = new javax.swing.JRadioButton();
        rbtnhepatitis = new javax.swing.JRadioButton();
        rbtnecardiaca = new javax.swing.JRadioButton();
        rbtnhipertencion = new javax.swing.JRadioButton();
        rbtnesanguinea = new javax.swing.JRadioButton();
        rbtnpendcrino = new javax.swing.JRadioButton();
        rbtnfreumatica = new javax.swing.JRadioButton();
        rbtntoseos = new javax.swing.JRadioButton();
        rbtndcerebral = new javax.swing.JRadioButton();
        rbtnpemocionales = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del Paciente");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        jLabel2.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Edad:");
        jLabel3.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Sexo:");
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Domicilio Particular:");
        jLabel5.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Telefono:");
        jLabel6.setFocusable(false);

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtNombre.setFocusable(false);

        cmbSexo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));
        cmbSexo.setFocusable(false);

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtEdad.setFocusable(false);

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtTelefono.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("Nro de Historia:");

        txtcedula.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcedulaFocusGained(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel26.setText("Cedula:");
        jLabel26.setFocusable(false);

        txtNroHist.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtNroHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroHistActionPerformed(evt);
            }
        });
        txtNroHist.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNroHistFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNroHistFocusLost(evt);
            }
        });
        txtNroHist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroHistKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroHistKeyTyped(evt);
            }
        });

        txtDomicilio.setEditable(false);
        txtDomicilio.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtDomicilio.setFocusable(false);

        cmbTCedPac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V-", "E-" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(txtDomicilio))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTCedPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNroHist)
                    .addComponent(txtcedula)
                    .addComponent(txtEdad)
                    .addComponent(cmbSexo, 0, 106, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroHist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTCedPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEstPorque.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblEstPorque.setText("¿Por qué?");
        lblEstPorque.setFocusable(false);

        tbtnEst.setText("No");
        tbtnEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnEstActionPerformed(evt);
            }
        });

        txtEstDes.setColumns(20);
        txtEstDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtEstDes.setRows(5);
        txtEstDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstDesKeyTyped(evt);
            }
        });
        jtxtEstDes.setViewportView(txtEstDes);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("¿Ha estado bajo medicacion en los ultimos años, aparte de los examenes de rutina?");
        jLabel10.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setText("¿Toma medicamentos Actualmente?");
        jLabel12.setFocusable(false);

        tbtnMed.setText("No");
        tbtnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnMedActionPerformed(evt);
            }
        });

        lblMedCuales.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblMedCuales.setText("¿Cuales?");
        lblMedCuales.setFocusable(false);

        txtMedDes.setColumns(20);
        txtMedDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtMedDes.setRows(5);
        txtMedDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedDesKeyTyped(evt);
            }
        });
        jtxtMedDes.setViewportView(txtMedDes);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setText("¿Ronca cuando duerme?");
        jLabel14.setFocusable(false);

        txtDolDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtDolDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDolDesKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setText("Es alérgico a:");
        jLabel15.setFocusable(false);

        rbtnPolvo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnPolvo.setText("Polvo");
        rbtnPolvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPolvoActionPerformed(evt);
            }
        });

        rbtnMed.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnMed.setText("Medicamentos");
        rbtnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMedActionPerformed(evt);
            }
        });

        rbtnAlimentos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnAlimentos.setText("alimentos");
        rbtnAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAlimentosActionPerformed(evt);
            }
        });

        txtAlerDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtAlerDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlerDesActionPerformed(evt);
            }
        });
        txtAlerDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlerDesKeyTyped(evt);
            }
        });

        rbtnOtros.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnOtros.setText("Otros:");
        rbtnOtros.setFocusable(false);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel17.setText("¿Qué toma normalmente para el dolor de cabeza?");
        jLabel17.setFocusable(false);

        tbtnRonca.setText("No");
        tbtnRonca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRoncaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setText("¿Respira por la boca?");
        jLabel18.setFocusable(false);

        tbtnResp.setText("No");
        tbtnResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRespActionPerformed(evt);
            }
        });

        cmbResCuando.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A veces", "De dia", "De noche" }));
        cmbResCuando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbResCuandoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel19.setText("¿Se resfria con frecuencia?");
        jLabel19.setFocusable(false);

        tbtnResfrio.setText("No");
        tbtnResfrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnResfrioActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel20.setText("¿Sufre de agmigdalitis o sinussitis?");
        jLabel20.setFocusable(false);

        tbtnAmigd.setText("No");
        tbtnAmigd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAmigdActionPerformed(evt);
            }
        });

        txtMastDes.setColumns(20);
        txtMastDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtMastDes.setRows(5);
        txtMastDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMastDesKeyTyped(evt);
            }
        });
        jtxtMastDes.setViewportView(txtMastDes);

        lblMastPorque.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblMastPorque.setText("¿Porqué?");
        lblMastPorque.setFocusable(false);

        tbtnMast.setText("No");
        tbtnMast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnMastActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel22.setText("¿Tiene dificultad para masticar o tragar?");
        jLabel22.setFocusable(false);

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel23.setText("¿Ha sido tratado por un alergeologo o especialistas del oido, nariz o garganta ?");
        jLabel23.setFocusable(false);

        tbtnOrl.setText("No");
        tbtnOrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnOrlActionPerformed(evt);
            }
        });

        lblOrlPorque.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblOrlPorque.setText("¿Porqué?");
        lblOrlPorque.setFocusable(false);

        txtOrlDes.setColumns(20);
        txtOrlDes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtOrlDes.setRows(5);
        txtOrlDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrlDesKeyTyped(evt);
            }
        });
        jtxtOrlDes.setViewportView(txtOrlDes);

        rbtnCirugia.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnCirugia.setText("Cirugia nasal");
        rbtnCirugia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCirugiaActionPerformed(evt);
            }
        });

        rbtnAmigd.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnAmigd.setText("Amigdalectomía");
        rbtnAmigd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAmigdActionPerformed(evt);
            }
        });

        rbtnAdenoi.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnAdenoi.setText("Adenoidectomía");
        rbtnAdenoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAdenoiActionPerformed(evt);
            }
        });

        fchOrl.setOpaque(false);

        lblOrlCuando.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblOrlCuando.setText("¿cuando?");
        lblOrlCuando.setFocusable(false);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(rbtnCirugia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAmigd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAdenoi))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tbtnOrl))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(lblOrlPorque)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxtOrlDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblOrlCuando)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fchOrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(tbtnMast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMastPorque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtMastDes, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(tbtnEst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEstPorque)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtEstDes, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(tbtnMed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMedCuales)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtMedDes, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDolDes, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rbtnOtros)
                                                .addComponent(rbtnPolvo))
                                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtnMed)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtnAlimentos))
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                    .addGap(57, 57, 57)
                                                    .addComponent(txtAlerDes, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(55, 55, 55)
                                .addComponent(tbtnResp))
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tbtnResfrio))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbtnRonca))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbtnAmigd)
                                .addGap(133, 133, 133))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(cmbResCuando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtnEst)
                        .addComponent(lblEstPorque))
                    .addComponent(jtxtEstDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtnMed)
                        .addComponent(lblMedCuales))
                    .addComponent(jtxtMedDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDolDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPolvo)
                    .addComponent(rbtnMed)
                    .addComponent(rbtnAlimentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlerDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnOtros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnRonca)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20)
                    .addComponent(tbtnAmigd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnResfrio)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tbtnResp)
                    .addComponent(cmbResCuando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtnMast)
                        .addComponent(lblMastPorque))
                    .addComponent(jtxtMastDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tbtnOrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrlPorque)
                            .addComponent(jtxtOrlDes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fchOrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnCirugia)
                            .addComponent(rbtnAmigd)
                            .addComponent(rbtnAdenoi)))
                    .addComponent(lblOrlCuando))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(lblEstPorque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnEst, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtxtEstDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnMed, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMedCuales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtxtMedDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDolDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnPolvo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnMed, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnAlimentos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtAlerDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnOtros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnRonca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnResp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbResCuando, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnResfrio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnAmigd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtxtMastDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMastPorque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnMast, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tbtnOrl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblOrlPorque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtxtOrlDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnCirugia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnAmigd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbtnAdenoi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fchOrl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblOrlCuando, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Historia Médica");
        jLabel8.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("Ha padecido alguna vez:");
        jLabel9.setFocusable(false);

        rbtnasma.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnasma.setText("Asma");
        rbtnasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnasmaActionPerformed(evt);
            }
        });

        rbtndiabetes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtndiabetes.setText("Diabetes");
        rbtndiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndiabetesActionPerformed(evt);
            }
        });

        rbtnanemia.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnanemia.setText("Anemia");
        rbtnanemia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnanemiaActionPerformed(evt);
            }
        });

        rbtnherpes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnherpes.setText("Herpes");
        rbtnherpes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnherpesActionPerformed(evt);
            }
        });

        rbtnepilepsia.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnepilepsia.setText("Epilepsia");
        rbtnepilepsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnepilepsiaActionPerformed(evt);
            }
        });

        rbtnhepatitis.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnhepatitis.setText("Hepatitis");
        rbtnhepatitis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnhepatitisActionPerformed(evt);
            }
        });

        rbtnecardiaca.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnecardiaca.setText("Enfermedad cardiaca");
        rbtnecardiaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnecardiacaActionPerformed(evt);
            }
        });

        rbtnhipertencion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnhipertencion.setText("Hipertencion");
        rbtnhipertencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnhipertencionActionPerformed(evt);
            }
        });

        rbtnesanguinea.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnesanguinea.setText("Enfermedad Sanguínea");
        rbtnesanguinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnesanguineaActionPerformed(evt);
            }
        });

        rbtnpendcrino.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnpendcrino.setText(" Problema endocrino");
        rbtnpendcrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnpendcrinoActionPerformed(evt);
            }
        });

        rbtnfreumatica.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnfreumatica.setText("Fiebre Reumática");
        rbtnfreumatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfreumaticaActionPerformed(evt);
            }
        });

        rbtntoseos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtntoseos.setText("Trastornos óseos");
        rbtntoseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtntoseosActionPerformed(evt);
            }
        });

        rbtndcerebral.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtndcerebral.setText("Daño Cerebral o Facial");
        rbtndcerebral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndcerebralActionPerformed(evt);
            }
        });

        rbtnpemocionales.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rbtnpemocionales.setText("Problemas Emocionales");
        rbtnpemocionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnpemocionalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnecardiaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnhipertencion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnesanguinea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnpendcrino))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnfreumatica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtntoseos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtndcerebral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnpemocionales))
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnasma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtndiabetes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnherpes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rbtnanemia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnepilepsia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnhepatitis)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnasma)
                    .addComponent(rbtndiabetes)
                    .addComponent(rbtnherpes)
                    .addComponent(rbtnanemia)
                    .addComponent(rbtnepilepsia)
                    .addComponent(rbtnhepatitis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnecardiaca)
                    .addComponent(rbtnhipertencion)
                    .addComponent(rbtnesanguinea)
                    .addComponent(rbtnpendcrino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnfreumatica)
                    .addComponent(rbtntoseos)
                    .addComponent(rbtndcerebral)
                    .addComponent(rbtnpemocionales))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/aceptar2.png"))); // NOI18N
        btnguardar.setToolTipText("Guardar");
        btnguardar.setContentAreaFilled(false);
        btnguardar.setDefaultCapable(false);
        btnguardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/aceptar3.png"))); // NOI18N
        btnguardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/aceptar1.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/limpiar2.png"))); // NOI18N
        btnlimpiar.setToolTipText("Limpiar");
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setDefaultCapable(false);
        btnlimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/limpiar3.png"))); // NOI18N
        btnlimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/limpiar1.png"))); // NOI18N
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/buscar2.png"))); // NOI18N
        btnbuscar.setToolTipText("Buscar");
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setDefaultCapable(false);
        btnbuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/buscar3.png"))); // NOI18N
        btnbuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/buscar1.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/actualizar2.png"))); // NOI18N
        btnactualizar.setToolTipText("Actualizar");
        btnactualizar.setContentAreaFilled(false);
        btnactualizar.setDefaultCapable(false);
        btnactualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/actualizar3.png"))); // NOI18N
        btnactualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/actualizar1.png"))); // NOI18N
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/borrar2.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        btneliminar.setContentAreaFilled(false);
        btneliminar.setDefaultCapable(false);
        btneliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/borrar3.png"))); // NOI18N
        btneliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/borrar1.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelar2.png"))); // NOI18N
        btncancelar.setToolTipText("Salir");
        btncancelar.setContentAreaFilled(false);
        btncancelar.setDefaultCapable(false);
        btncancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelar3.png"))); // NOI18N
        btncancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelar3.png"))); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusGained
        // TODO add your handling code here:
        focoBusq="nroCedula";
        txtcedula.selectAll();

    }//GEN-LAST:event_txtcedulaFocusGained

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        // TODO add your handling code here:
        validarDigitos(txtcedula,evt);

        //validarCedula(txtcedula,evt);

    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtNroHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroHistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroHistActionPerformed

    private void txtNroHistFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNroHistFocusGained
        // TODO add your handling code here:
        focoBusq="nroHistorial";
        txtNroHist.select(0, txtNroHist.getText().length());

    }//GEN-LAST:event_txtNroHistFocusGained

    private void txtNroHistFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNroHistFocusLost
        // TODO add your handling code here:
        txtNroHist.setText(nroHistFormateado(Integer.valueOf(txtNroHist.getText())));
    }//GEN-LAST:event_txtNroHistFocusLost

    private void txtNroHistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroHistKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroHistKeyPressed

    private void txtNroHistKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroHistKeyTyped
        // TODO add your handling code here:

        validarDigitos(txtNroHist,evt);

    }//GEN-LAST:event_txtNroHistKeyTyped

    private void tbtnEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnEstActionPerformed
        // TODO add your handling code here:
        configurarTbtnEst();
    }//GEN-LAST:event_tbtnEstActionPerformed

    private void txtEstDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtEstDes, evt, 30);
    }//GEN-LAST:event_txtEstDesKeyTyped

    private void tbtnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMedActionPerformed
        // TODO add your handling code here:
        configurarTbtnMed();
    }//GEN-LAST:event_tbtnMedActionPerformed

    private void txtMedDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtMedDes, evt, 30);
    }//GEN-LAST:event_txtMedDesKeyTyped

    private void txtDolDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDolDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtDolDes, evt, 30);
    }//GEN-LAST:event_txtDolDesKeyTyped

    private void rbtnPolvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPolvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPolvoActionPerformed

    private void rbtnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMedActionPerformed

    private void rbtnAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAlimentosActionPerformed

    private void txtAlerDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlerDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlerDesActionPerformed

    private void txtAlerDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlerDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtAlerDes, evt, 36);
    }//GEN-LAST:event_txtAlerDesKeyTyped

    private void tbtnRoncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRoncaActionPerformed
        // TODO add your handling code here:
        configurarTbtnRonca();
    }//GEN-LAST:event_tbtnRoncaActionPerformed

    private void tbtnRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRespActionPerformed
        // TODO add your handling code here:
        configurarTbtnResp();
    }//GEN-LAST:event_tbtnRespActionPerformed

    private void cmbResCuandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbResCuandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbResCuandoActionPerformed

    private void tbtnResfrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnResfrioActionPerformed
        // TODO add your handling code here:
        configurarTbtnResfrio();
    }//GEN-LAST:event_tbtnResfrioActionPerformed

    private void tbtnAmigdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAmigdActionPerformed
        // TODO add your handling code here:
        configurarTbtnAmigd();
    }//GEN-LAST:event_tbtnAmigdActionPerformed

    private void txtMastDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMastDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtMastDes, evt, 30);
    }//GEN-LAST:event_txtMastDesKeyTyped

    private void tbtnMastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMastActionPerformed
        // TODO add your handling code here:
        configurarTbtnMast();
    }//GEN-LAST:event_tbtnMastActionPerformed

    private void tbtnOrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnOrlActionPerformed
        // TODO add your handling code here:
        configurarTbtnOrl();
    }//GEN-LAST:event_tbtnOrlActionPerformed

    private void txtOrlDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrlDesKeyTyped
        // TODO add your handling code here:
        validarLimite(txtOrlDes, evt, 30);
    }//GEN-LAST:event_txtOrlDesKeyTyped

    private void rbtnCirugiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCirugiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCirugiaActionPerformed

    private void rbtnAmigdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAmigdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAmigdActionPerformed

    private void rbtnAdenoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAdenoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAdenoiActionPerformed

    private void rbtnasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnasmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnasmaActionPerformed

    private void rbtndiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtndiabetesActionPerformed

    private void rbtnanemiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnanemiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnanemiaActionPerformed

    private void rbtnherpesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnherpesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnherpesActionPerformed

    private void rbtnepilepsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnepilepsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnepilepsiaActionPerformed

    private void rbtnhepatitisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnhepatitisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnhepatitisActionPerformed

    private void rbtnecardiacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnecardiacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnecardiacaActionPerformed

    private void rbtnhipertencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnhipertencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnhipertencionActionPerformed

    private void rbtnesanguineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnesanguineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnesanguineaActionPerformed

    private void rbtnpendcrinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnpendcrinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnpendcrinoActionPerformed

    private void rbtnfreumaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfreumaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnfreumaticaActionPerformed

    private void rbtntoseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtntoseosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtntoseosActionPerformed

    private void rbtndcerebralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndcerebralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtndcerebralActionPerformed

    private void rbtnpemocionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnpemocionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnpemocionalesActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        inicializarAtributos();
        limpiarPantalla();
        obtenerNroHistorial();

    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        leerdatos();
        buscar();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        deshabilitarHist();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox cmbResCuando;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbTCedPac;
    private com.toedter.calendar.JDateChooser fchOrl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jtxtEstDes;
    private javax.swing.JScrollPane jtxtMastDes;
    private javax.swing.JScrollPane jtxtMedDes;
    private javax.swing.JScrollPane jtxtOrlDes;
    private javax.swing.JLabel lblEstPorque;
    private javax.swing.JLabel lblMastPorque;
    private javax.swing.JLabel lblMedCuales;
    private javax.swing.JLabel lblOrlCuando;
    private javax.swing.JLabel lblOrlPorque;
    private javax.swing.JRadioButton rbtnAdenoi;
    private javax.swing.JRadioButton rbtnAlimentos;
    private javax.swing.JRadioButton rbtnAmigd;
    private javax.swing.JRadioButton rbtnCirugia;
    private javax.swing.JRadioButton rbtnMed;
    private javax.swing.JLabel rbtnOtros;
    private javax.swing.JRadioButton rbtnPolvo;
    private javax.swing.JRadioButton rbtnanemia;
    private javax.swing.JRadioButton rbtnasma;
    private javax.swing.JRadioButton rbtndcerebral;
    private javax.swing.JRadioButton rbtndiabetes;
    private javax.swing.JRadioButton rbtnecardiaca;
    private javax.swing.JRadioButton rbtnepilepsia;
    private javax.swing.JRadioButton rbtnesanguinea;
    private javax.swing.JRadioButton rbtnfreumatica;
    private javax.swing.JRadioButton rbtnhepatitis;
    private javax.swing.JRadioButton rbtnherpes;
    private javax.swing.JRadioButton rbtnhipertencion;
    private javax.swing.JRadioButton rbtnpemocionales;
    private javax.swing.JRadioButton rbtnpendcrino;
    private javax.swing.JRadioButton rbtntoseos;
    private javax.swing.JToggleButton tbtnAmigd;
    private javax.swing.JToggleButton tbtnEst;
    private javax.swing.JToggleButton tbtnMast;
    private javax.swing.JToggleButton tbtnMed;
    private javax.swing.JToggleButton tbtnOrl;
    private javax.swing.JToggleButton tbtnResfrio;
    private javax.swing.JToggleButton tbtnResp;
    private javax.swing.JToggleButton tbtnRonca;
    private javax.swing.JTextField txtAlerDes;
    private javax.swing.JTextField txtDolDes;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextArea txtEstDes;
    private javax.swing.JTextArea txtMastDes;
    private javax.swing.JTextArea txtMedDes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroHist;
    private javax.swing.JTextArea txtOrlDes;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables
}
